### ISSUE TITLE
Non-linear volume control

### ISSUE THREAD

**Issue by gg-mmill** [vzze/volume-control#8]
Hello, thanks for this great extension !

Do you think it would be relevant to have a non-linear scale for volume control ? I have to go down to about 10/100, which about halves the perceived volume (but this may vary between browsers / OSs).  I'll have a look at how this could be done in a few days.

Also I suggest you add the link to this repo in the description, so that it's easier to contact you (and also shows that the extension is open-source, which is great).

**Comment by vzze** [comment]
> Also I suggest you add the link to this repo in the description, so that it's easier to contact you (and also shows that the extension is open-source, which is great).

Done, the description of the [extension](https://addons.mozilla.org/en-US/firefox/addon/volume-control-tabs/) should be updated.

> Do you think it would be relevant to have a non-linear scale for volume control ? I have to go down to about 10/100, which about halves the perceived volume (but this may vary between browsers / OSs). I'll have a look at how this could be done in a few days.

It might be possible if the method for setting volume for each audio/video element is changed, however from what I know this is the only possible way.

```js
document.querySelectorAll("video, audio").forEach(elem => elem.volume = ${data.volumes[tabId] / 100})
```

There is also the other problem of websites altering what "100%" is for example what might appear as a maxed out audio bar on Youtube is actually only 70% for the extension itself. (At least this used to be a problem it seems it was fixed some time ago for Youtube) Which is why it might feel like the extension's bar might have a non-linear scale.

You can use this line in the browser's console to check if volumes line up with what's shown on the extension/audio bar of the website you're using.

```js
document.querySelectorAll("video, audio").forEach(elem => console.log(elem.volume))
```

I'll look more thoroughly into this in the next couple of days, thanks for reporting and using my extension.

And if you can provide a list of websites where you've used/tested the extension that'd be amazing.

**Comment by sapristi** [comment]
(me again,  I used my work account by mistake when opening the issue)

I only used the extension on https://www.canalb.fr for now. Indeed the reported volume in the browser is exactly what is set by your extension (divided by 100), but I guess what could be done would be to transform the value (i.e. if the extension is at 50 , set the browser volume to 0.5^2 = 0.25)
